name: Cleanup Published Invites

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minute
  workflow_dispatch:

jobs:
  cleanup_job:
    runs-on: ubuntu-latest

    steps:
      - name: Call Cleanup API
        run: |
          curl --fail --silent --show-error --location --request GET 'https://wedding-invite-backend-r0zm.onrender.com/cleanup'
